[project]
name = "ailoy-gradio-chatbot-example"
version = "0.1.0"
description = "Ailoy + Gradio integration example"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ailoy-py",
    "gradio>=5.31.0",
]

[tool.uv.sources]
ailoy-py = { path = "../../bindings/python" }
