[package]
name = "ailoy-macros"
version = "0.2.0-rc.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
async-trait = "0.1.89"
convert_case = "0.8.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
